### ISSUE TITLE
Kubectl en Windows

### ISSUE THREAD

**Issue by antgamdia** [bitnami/kubernetes-workshop#1]
Para quien quiera evitar usar gcloud y kubectl en linux, se puede hacer lo siguiente:

1. Instalar gcloud y autenticarse
2. Ejecutar: `gcloud container clusters get-credentials cluster-1` (cluster-1 o el nombre del clúster de cada uno)
3. Eso te crea un directorio .kube en el home del usuario. Entrar ahí y editar ver el contenido del fichero config
4. Descargar una versión compilada de kubectl (o compilarlo en Go). [Ejemplo].(https://github.com/eirslett/kubectl-windows)
5. En abrir terminar y ejecutar kubectl con el argumento `--kubeconfig="rutaDelPaso3"`

Listo :)

**Comment by j-fuentes** [comment]
Muchas gracias @antgamdia, lo tendremos en cuenta para la próxima vez ;-)
